title:        "Lidmila Maršálková - fotografka"
description:  "Nejdražší fotograf vždy nemusí znamenat nejlepší výsledek. Zkuste proto začínající fotografku s nízkými cenami a příjemným vystupováním. Ať už mě navštívíte ve foto ateliéru na Praze 4 nebo mě pozvete na vaši společenskou událost, mohu zaručit, že s výslednými fotografiemi budete spokojeni."
permalink:    pretty
exclude:      ['*.txt']

gallery:
  dir: images
  thumbnail_size:
    x: 500
    y: 500
